# Generated by Django 3.1.7 on 2021-03-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('Slot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Occupancy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='park',
            fields=[
                ('Park_Id', models.AutoField(primary_key=True, serialize=False)),
                ('License_No', models.CharField(max_length=20)),
                ('VR_No', models.CharField(max_length=20)),
                ('Entry_Date_Time', models.DateTimeField()),
                ('Depart_Date_Time', models.DateTimeField()),
                ('Actual_Depart_Date_Time', models.DateTimeField(blank=True)),
                ('Amount_Paid', models.IntegerField()),
                ('Slot_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.slot')),
            ],
        ),
    ]
