# Generated by Django 3.1.7 on 2021-03-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_park_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='Slot_id',
            new_name='Slot_Id',
        ),
    ]
